### ISSUE TITLE
Matrix Strategy Jobs are merged together

### ISSUE THREAD

**Issue by ChristopherHX** [SanjulaGanepola/github-local-actions#106]
### Github Local Actions Version

dev

### Act Version

0.2.69

### Workflow Content

```yml
name: Help
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        ok:
        - "Hello World"
        - "Bye world"
    steps:
    - run: echo '${{ github.actor }}'
    - run: echo '${{ vars.TEST }}'
    - run: echo '${{ secrets.test && github.event_name }}'
      if: false
    - uses: actions/github-script@HEAD
      with:
        script: |
          console.log('Test 2024-11-27T18:41:43.2689480Z')
          console.log('Test 2024-11-27T18:41:43.2689480Z')
        github-token: none
    - run: "echo '\nTest 2024-11-27T18:41:43.2689480Z'"
```

### Act Command Used

```sh
act --workflows ".github/workflows/main.yml" --secret-file "" --var TEST=$PATH-batch --var-file "" --input-file "" --platform self-hosted=-self-hosted --eventpath "~/Documents/doc/payload.json" --actor bot
```

### Bug Description

All matrix jobs are merged in a single job under the same jobid
