### ISSUE TITLE
Workspaces with many projects can cause lag and config changes to be lost

### ISSUE THREAD

**Issue by Makeshift** [SanjulaGanepola/github-local-actions#174]
### Github Local Actions Version

v1.2.2

### Act Version

0.2.74

### Workflow Content

```yml

```

### Act Command Used

```sh

```

### Act Command Output

```sh

```

### Bug Description

Changing any configuration within the UI (such as enabling/disabling an option) in a workspace causes a long refresh, during which any further changes will be reverted. In this workspace, there's about ~30 workflows total.

Video:

https://github.com/user-attachments/assets/cc1e9e3e-ef79-4bef-bceb-5e83a3527543

### Act Bug Report

```yml
act version:            0.2.74
GOOS:                   linux
GOARCH:                 amd64
NumCPU:                 22
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        /var/run/docker.sock
Config files:
        .actrc:
                -P ebx-tiny=060610571733.dkr.ecr.eu-west-1.amazonaws.com/ebx-actions-runner:latest
                -P ebx-small=060610571733.dkr.ecr.eu-west-1.amazonaws.com/ebx-actions-runner:latest
                -P ebx-medium=060610571733.dkr.ecr.eu-west-1.amazonaws.com/ebx-actions-runner:latest
                -P ebx-large=060610571733.dkr.ecr.eu-west-1.amazonaws.com/ebx-actions-runner:latest
                -P ebx-xlarge=060610571733.dkr.ecr.eu-west-1.amazonaws.com/ebx-actions-runner:latest
                --artifact-server-path ~/.cache/act/artifacts
                --env AWS_REGION=eu-west-1
                --env AWS_DEFAULT_REGION=eu-west-1
                --env CACHE_BUCKET=gha-runners-prod-ebx-bucket
                --env CACHE_BUCKET_REGION=eu-west-1
Build info:
        Go version:            go1.23.5
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.74 -X main.commit=3f741df6bcf35bafe16247e6dcb3072c5a481977 -X main.date=2025-02-10T06:52:17Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 linux
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         3f741df6bcf35bafe16247e6dcb3072c5a481977
                vcs.time:             2025-02-10T04:34:35Z
                vcs.modified:         false
Docker Engine:
        Engine version:        27.3.1
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlayfs
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.15.167.4-microsoft-standard-WSL2
        OS CPU:                22
        OS memory:             48175 MB
        Security options:
                name=seccomp,profile=unconfined
```
