### ISSUE TITLE
Nothig happens after `using DockerAuthConfig authentication for docker pull`

### ISSUE THREAD

**Issue by see7e** [SanjulaGanepola/github-local-actions#192]
### Github Local Actions Version

v1.2.5

### Act Version

0.2.75

### Workflow Content

```yml
name: Docs Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  translation-consistency:
    name: Translation Consistency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grant execute permissions
        run: chmod +x ./.github/workflows/scripts/*.sh
      - name: Check translation consistency
        run: ./.github/workflows/scripts/check_translations.sh --debug
```

### Act Command Used

```sh
act --workflows ".github/workflows/docs-test.yml" --job "translation-consistency" --secret GITHUB_TOKEN --secret-file "" --var-file "" --input-file "" --eventpath ""
```

### Act Command Output

```sh
*  Executing task: GitHub Local Actions: Docs Check/Translation Consistency Check #1 

act --workflows ".github/workflows/docs-test.yml" --job "translation-consistency" --secret GITHUB_TOKEN --secret-file "" --var-file "" --input-file "" --eventpath ""

Using docker host 'npipe:////./pipe/docker_engine', and daemon socket 'npipe:////./pipe/docker_engine'
[Docs Check/Translation Consistency Check] ⭐ Run Set up job
[Docs Check/Translation Consistency Check] 🚀  Start image=catthehacker/ubuntu:full-latest
[Docs Check/Translation Consistency Check]   🐳  docker pull image=catthehacker/ubuntu:full-latest platform= username= forcePull=true
[Docs Check/Translation Consistency Check] using DockerAuthConfig authentication for docker pull

Docs Check/Translation Consistency Check #1 was interrupted.

 *  The terminal process terminated with exit code: 1.
```

### Act Bug Report

```yml
> act --bug-report
act version:            0.2.75
GOOS:                   windows
GOARCH:                 amd64
NumCPU:                 6
Docker host:            DOCKER_HOST environment variable is not set
Sockets found:
        \\.\pipe\docker_engine(broken)
Config files:
        C:\Users\User\AppData\Local\act\actrc:
                -P ubuntu-latest=catthehacker/ubuntu:full-latest
                -P ubuntu-22.04=catthehacker/ubuntu:full-22.04
                -P ubuntu-20.04=catthehacker/ubuntu:full-20.04
                -P ubuntu-18.04=catthehacker/ubuntu:full-18.04
Build info:
        Go version:            go1.23.6
        Module path:           github.com/nektos/act
        Main version:          (devel)
        Main path:             github.com/nektos/act
        Main checksum:
        Build settings:
                -buildmode:           exe
                -compiler:            gc
                -ldflags:             -s -w -X main.version=0.2.75 -X main.commit=bd97dc8d9422a8b04e6193c6c86afa8a7a693fdf -X main.date=2025-03-01T02:31:09Z -X main.builtBy=goreleaser
                CGO_ENABLED:          0
                GOARCH:               amd64
                GOOS:                 windows
                GOAMD64:              v1
                vcs:                  git
                vcs.revision:         bd97dc8d9422a8b04e6193c6c86afa8a7a693fdf
                vcs.time:             2025-03-01T02:30:53Z
                vcs.modified:         false
Docker Engine:
        Engine version:        27.2.0
        Engine runtime:        runc
        Cgroup version:        1
        Cgroup driver:         cgroupfs
        Storage driver:        overlayfs
        Registry URI:          https://index.docker.io/v1/
        OS:                    Docker Desktop
        OS type:               linux
        OS version:
        OS arch:               x86_64
        OS kernel:             5.15.153.1-microsoft-standard-WSL2
        OS CPU:                6
        OS memory:             7912 MB
        Security options:
                name=seccomp,profile=unconfined
```

### Bug Description

Nothing happens after running jobs or full workflows, it stays for long periods of time until manual interruption.
