### ISSUE TITLE
Cannot run workflow from public archived repository (Unable to clone: [...] authentication required)

### ISSUE THREAD

**Issue by troys-code** [SanjulaGanepola/github-local-actions#201]
### Github Local Actions Version

 1.2.5

### Act Version

act version 0.2.76

### GitHub Repository Link

https://github.com/troy-lamerton/BeepBoopBot

### Workflow Content

```yml
name: Deploy static content to Cloudflare Pages CDN

on:
  # Runs on pushes targeting the default branch and only when
  # changes are made to files within the ./webpage folder
  push:
    branches: ["main"]
    paths:
      - './webpage/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build the static assets
      - name: Build
        run: npm ci --legacy-peer-deps && npm run build
        working-directory: ./

      # Publish to https://beepboopbot.pages.dev/
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: beepboopbot # See projects using CLI `npx wrangler pages project list`
          directory: ./webpage # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

### Act Command Used

```sh
act --workflows ".github/workflows/deploy.cloudflare.yml" --job "deploy" --secret-file "" --var-file "" --input-file "" --eventpath ""
```

### Act Command Output

```sh
*  Executing task: GitHub Local Actions: Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages #2 

act --workflows ".github/workflows/deploy.cloudflare.yml" --job "deploy" --secret-file "" --var-file "" --input-file "" --eventpath ""

Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock'
level=warning msg= ⚠ You are using Apple M-series chip and you have not specified container architecture, you might encounter issues while running act. If so, try running it with '--container-architecture linux/amd64'. ⚠
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] ⭐ Run Set up job
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] 🚀  Start image=node:16-buster-slim
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   🐳  docker pull image=node:16-buster-slim platform= username= forcePull=true
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   🐳  docker create image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   🐳  docker run image=node:16-buster-slim platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   ✅  Success - Set up job
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   ☁  git clone 'https://github.com/cloudflare/pages-action' # ref=v1
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] Unable to clone https://github.com/cloudflare/pages-action refs/heads/v1: authentication required: Invalid username or password.
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] authentication required: Invalid username or password.
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] ⭐ Run Complete job
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages]   ✅  Success - Complete job
[Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages] 🏁  Job failed
Error: authentication required: Invalid username or password.

Deploy static content to Cloudflare Pages CDN/Deploy to Cloudflare Pages #2 exited with exit code 1.

 *  The terminal process terminated with exit code: 1.
```

### Act Bug Report

```yml

```

### Bug Description

**Expected behavfiour**

I should be able to click Run button and it runs the action, even if workflow repository is archived.

**Relevant error**

```txt
Unable to clone https://github.com/cloudflare/pages-action refs/heads/v1: authentication required: Invalid username or password.
```

The repository at https://github.com/cloudflare/pages-action is **public and archived**.

To clone this public repository, I believe Github requires you to be authenticated (using username & password or token).

**Possible solution**

When it clones repository it can use my personal github user.

Perhaps the extension could:

- show an "Enter GitHub token" textbox, and pass this token to `nekos/act`
