### ISSUE TITLE
Add support for GitHub Token

### ISSUE THREAD

**Issue by SanjulaGanepola** [SanjulaGanepola/github-local-actions#94]
https://nektosact.com/usage/index.html#github_token

**Comment by SanjulaGanepola** [comment]
@ChristopherHX When I run the following command in Git Bash it works, but it fails using Command Prompt. When I run `gh auth token` alone, it can generate the token successfully. Any idea why?

**Command:**
```sh
act --workflows ".github/workflows/release.yaml" --secret GITHUB_TOKEN="$(gh auth token)"
```

**Workflow:**
```yml
name: Create GitHub Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
```

**Output:**
```sh
time="2025-02-08T15:32:13-05:00" level=info msg="Using docker host 'npipe:////./pipe/docker_engine', and daemon socket 'npipe:////./pipe/docker_engine'"
[Create GitHub Release/Create Release] 🚀  Start image=catthehacker/ubuntu:act-latest
[Create GitHub Release/Create Release]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Create GitHub Release/Create Release] using DockerAuthConfig authentication for docker pull
[Create GitHub Release/Create Release]   🐳  docker create image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Create GitHub Release/Create Release]   🐳  docker run image=catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Create GitHub Release/Create Release]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[Create GitHub Release/Create Release]   ☁  git clone 'https://github.com/actions/create-release' # ref=v1
[Create GitHub Release/Create Release] Cleaning up container for job Create Release
[Create GitHub Release/Create Release] 🏁  Job succeeded
Error: authentication required
```
